# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 20

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30

[[main]]
  name = "Awards"
  url = "#accomplishments"
  weight = 40

[[main]]
  name = "Certifications"
  url = "#contact"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "Resume"
   url = "https://docs.google.com/document/d/1_3KQ49ak7WtOuNZaM0BB4M61RnLAEJbiahvzHtnYuvM/export?format=pdf"
   weight = 70
